name: CI

env:
  HUSKY: 0

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Pipelines:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['lint', 'build']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: |
            **/yarn.lock
            **/.yarn/cache

      - name: Enable Yarn Berry
        run: |
          npm install -g corepack
          corepack enable
          yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Run commands
        run: yarn ${{ matrix.command }}
